2018-06-28 12:58:18.144 [57187] main/101/router C> Tarantool 2.0.4-314-g1695215b0
2018-06-28 12:58:18.145 [57187] main/101/router C> log level 5
2018-06-28 12:58:18.146 [57187] main/101/router I> mapping 117440512 bytes for memtx tuple arena...
2018-06-28 12:58:18.146 [57187] main/101/router I> mapping 134217728 bytes for vinyl tuple arena...
2018-06-28 12:58:18.149 [57187] iproto/101/main I> binary: bound to [::]:3301
2018-06-28 12:58:18.149 [57187] main/101/router I> initializing an empty data directory
2018-06-28 12:58:18.153 [57187] snapshot/101/main I> saving snapshot `./data/router/00000000000000000000.snap.inprogress'
2018-06-28 12:58:18.154 [57187] snapshot/101/main I> done
2018-06-28 12:58:18.155 [57187] main/101/router I> ready to accept requests
2018-06-28 12:58:18.155 [57187] main/107/checkpoint_daemon I> started
2018-06-28 12:58:18.155 [57187] main/107/checkpoint_daemon I> scheduled the next snapshot at Thu Jun 28 14:57:58 2018
2018-06-28 12:58:18.156 [57187] main/101/router I> Box has been configured
2018-06-28 12:58:18.159 [57187] main/112/127.0.0.1:3303 (net.box) I> connected to 127.0.0.1:3303
2018-06-28 12:58:18.159 [57187] main/113/127.0.0.1:3304 (net.box) I> connected to 127.0.0.1:3304
2018-06-28 12:58:18.160 [57187] main/114/127.0.0.1:3302 (net.box) I> connected to 127.0.0.1:3302
2018-06-28 12:58:18.161 [57187] main/115/127.0.0.1:3301 (net.box) I> connected to 127.0.0.1:3301
2018-06-28 12:58:18.161 [57187] main/101/router I> Start failover fiber
2018-06-28 12:58:18.161 [57187] main/116/vshard.failover I> New replica storage_2_a(storage@127.0.0.1:3303) for replicaset(uuid="ac522f65-aa94-4134-9f64-51ee384f1a54", master=storage_2_a(storage@127.0.0.1:3303))
2018-06-28 12:58:18.161 [57187] main/116/vshard.failover I> New replica storage_1_a(storage@127.0.0.1:3301) for replicaset(uuid="cbf06940-0790-498b-948d-042b62cf3d29", master=storage_1_a(storage@127.0.0.1:3301))
2018-06-28 12:58:18.161 [57187] main/116/vshard.failover I> All replicas are ok
2018-06-28 12:58:18.161 [57187] main/116/vshard.failover I> Failovering step is finished. Schedule next after 1.000000 seconds
2018-06-28 12:58:18.161 [57187] main/101/router I> Start discovery fiber
2018-06-28 12:58:18.167 [57187] main/118/http/127.0.0.1:8585 I> started
2018-06-28 12:58:18.167 [57187] main C> entering the event loop
2018-06-28 12:58:19.162 [57187] main/116/vshard.failover I> All replicas are ok
2018-06-28 12:58:19.197 [57187] main/119/console/unix/: I> Buckets from 1 to 1500 are bootstrapped on "ac522f65-aa94-4134-9f64-51ee384f1a54"
2018-06-28 12:58:19.202 [57187] main/119/console/unix/: I> Buckets from 1501 to 3000 are bootstrapped on "cbf06940-0790-498b-948d-042b62cf3d29"
2018-06-28 12:58:28.171 [57187] main/117/discovery_fiber I> Updated replicaset(uuid="cbf06940-0790-498b-948d-042b62cf3d29", master=storage_1_a(storage@127.0.0.1:3301)) buckets: was 0, became 1500
2018-06-28 12:58:38.175 [57187] main/117/discovery_fiber I> Updated replicaset(uuid="ac522f65-aa94-4134-9f64-51ee384f1a54", master=storage_2_a(storage@127.0.0.1:3303)) buckets: was 0, became 1500
2018-06-28 13:00:28.776 [57187] main/121/http/127.0.0.1:53340 I> GET /users?user_id=2&name=peter
2018-06-28 13:00:33.257 [57187] main/121/http/127.0.0.1:53340 I> POST /users?user_id=2&name=peter
2018-06-28 13:00:36.145 [57187] main/121/http/127.0.0.1:53340 I> GET /users?user_id=2&name=peter
2018-06-28 13:00:43.578 [57187] main/121/http/127.0.0.1:53340 I> POST /users?user_id=2&name=peter
2018-06-28 13:00:43.578 [57187] main/121/http/127.0.0.1:53340 replicaset.lua:239 E> Exception during calling 'vshard.storage.call' on 'storage_2_a(storage@127.0.0.1:3303)': Duplicate key exists in unique index 'user_id' in space 'user'
